 SUBROUTINE TEMPERATURE: R1 > R2, bad sample or               wro
 RECOVERABLE error, program continuing
 Error type:      1
 
 SUBROUTINE TEMPERATURE: R1 > R2, bad sample or               wro
 RECOVERABLE error, program continuing
 Error type:      1
 
 SUBROUTINE TEMPERATURE: R1 > R2, bad sample or               wro
 RECOVERABLE error, program continuing
 Error type:      1
 
 SUBROUTINE TEMPERATURE: R1 > R2, bad sample or               wro
 RECOVERABLE error, program continuing
 Error type:      1
 
